---
- name: create merged farmer config information
  set_fact:
    storj_farmer_configs_merged: "{{ storj_farmer_configs_merged | default('[]') }} + [ {{ merged_item }} ]"
  vars:
    config_path: "{{ storj_farmer_config_dir }}/{{ item.payment_address }}.config"
    merged_item: "{{ {'config_path': config_path } | combine(item) }}"
  with_items:
    - "{{ storj_farmer_configs }}"

- name: reassign merged facts back to original configs (pass 1)
  set_fact:
    storj_farmer_configs: "{{ storj_farmer_configs_merged }}"

- name: check for existing storjshare configs
  stat:
    path: "{{ item.config_path }}"
  register: storj_farmer_configs_stat
  with_items:
    - "{{ storj_farmer_configs }}"

- name: reset merged configs
  set_fact:
    storj_farmer_configs_merged: []

- name: create merged farmer config information
  set_fact:
    storj_farmer_configs_merged: "{{ storj_farmer_configs_merged | default('[]') }} + [ {{ item.0 | combine({ 'config_path_exists': item.1.stat.exists }) }} ]"
  with_together:
    - "{{ storj_farmer_configs }}"
    - "{{ storj_farmer_configs_stat.results }}"

- name: reassign merged facts back to original configs
  set_fact:
    storj_farmer_configs: "{{ storj_farmer_configs_merged }}"
