---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - python
    - build-essential

- name: install storjshare
  npm:
    name: storjshare-daemon
    state: present
    global: yes

- name: ensure storjshare daemon is running
  command: storjshare daemon
  register: daemon_result
  changed_when: "'* starting daemon' in daemon_result.stdout"
